services:
  udp-server:
    build:
      context: servers/udp_server
    ports:
      - "12345:12345/udp"
    restart: unless-stopped

  tcp-server:
    build:
      context: servers/tcp_server
    ports:
      - "23456:23456/tcp"
    restart: unless-stopped

  quic-server:
    build:
      context: servers/quic_server
    ports:
      - "4433:4433/udp"
    restart: unless-stopped
